staty = [
    {
        "name": "Afghanistan",
        "capital": "Kabul",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 27657145,
        "area": 652230.0,
        "gini": 27.8,
    },
    {
        "name": "Åland Islands",
        "capital": "Mariehamn",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 28875,
        "area": 1580.0,
    },
    {
        "name": "Albania",
        "capital": "Tirana",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 2886026,
        "area": 28748.0,
        "gini": 34.5,
    },
    {
        "name": "Algeria",
        "capital": "Algiers",
        "region": "Africa",
        "subregion": "Northern Africa",
        "population": 40400000,
        "area": 2381741.0,
        "gini": 35.3,
    },
    {
        "name": "American Samoa",
        "capital": "Pago Pago",
        "region": "Oceania",
        "subregion": "Polynesia",
        "population": 57100,
        "area": 199.0,
    },
    {
        "name": "Andorra",
        "capital": "Andorra la Vella",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 78014,
        "area": 468.0,
    },
    {
        "name": "Angola",
        "capital": "Luanda",
        "region": "Africa",
        "subregion": "Middle Africa",
        "population": 25868000,
        "area": 1246700.0,
        "gini": 58.6,
    },
    {
        "name": "Anguilla",
        "capital": "The Valley",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 13452,
        "area": 91.0,
    },
    {
        "name": "Antarctica",
        "capital": "",
        "region": "Polar",
        "subregion": "",
        "population": 1000,
        "area": 14000000.0,
    },
    {
        "name": "Antigua and Barbuda",
        "capital": "Saint John's",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 86295,
        "area": 442.0,
    },
    {
        "name": "Argentina",
        "capital": "Buenos Aires",
        "region": "Americas",
        "subregion": "South America",
        "population": 43590400,
        "area": 2780400.0,
        "gini": 44.5,
    },
    {
        "name": "Armenia",
        "capital": "Yerevan",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 2994400,
        "area": 29743.0,
        "gini": 30.9,
    },
    {
        "name": "Aruba",
        "capital": "Oranjestad",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 107394,
        "area": 180.0,
    },
    {
        "name": "Australia",
        "capital": "Canberra",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": 24117360,
        "area": 7692024.0,
        "gini": 30.5,
    },
    {
        "name": "Austria",
        "capital": "Vienna",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 8725931,
        "area": 83871.0,
        "gini": 26.0,
    },
    {
        "name": "Azerbaijan",
        "capital": "Baku",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 9730500,
        "area": 86600.0,
        "gini": 33.7,
    },
    {
        "name": "Bahamas",
        "capital": "Nassau",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 378040,
        "area": 13943.0,
    },
    {
        "name": "Bahrain",
        "capital": "Manama",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 1404900,
        "area": 765.0,
    },
    {
        "name": "Bangladesh",
        "capital": "Dhaka",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 161006790,
        "area": 147570.0,
        "gini": 32.1,
    },
    {
        "name": "Argentina",
        "capital": "Buenos Aires",
        "region": "Americas",
        "subregion": "South America",
        "population": 43590400,
        "area": 2780400.0,
        "gini": 44.5,
    },
    {
        "name": "Armenia",
        "capital": "Yerevan",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 2994400,
        "area": 29743.0,
        "gini": 30.9,
    },
    {
        "name": "Aruba",
        "capital": "Oranjestad",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 107394,
        "area": 180.0,
    },
    {
        "name": "Australia",
        "capital": "Canberra",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": 24117360,
        "area": 7692024.0,
        "gini": 30.5,
    },
    {
        "name": "Austria",
        "capital": "Vienna",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 8725931,
        "area": 83871.0,
        "gini": 26.0,
    },
    {
        "name": "Azerbaijan",
        "capital": "Baku",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 9730500,
        "area": 86600.0,
        "gini": 33.7,
    },
    {
        "name": "Bahamas",
        "capital": "Nassau",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 378040,
        "area": 13943.0,
    },
    {
        "name": "Bahrain",
        "capital": "Manama",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 1404900,
        "area": 765.0,
    },
    {
        "name": "Bangladesh",
        "capital": "Dhaka",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 161006790,
        "area": 147570.0,
        "gini": 32.1,
    },
    {
        "name": "Barbados",
        "capital": "Bridgetown",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 285000,
        "area": 430.0,
    },
    {
        "name": "Belarus",
        "capital": "Minsk",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "population": 9498700,
        "area": 207600.0,
        "gini": 26.5,
    },
    {
        "name": "Belgium",
        "capital": "Brussels",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 11319511,
        "area": 30528.0,
        "gini": 33.0,
    },
    {
        "name": "Belize",
        "capital": "Belmopan",
        "region": "Americas",
        "subregion": "Central America",
        "population": 370300,
        "area": 22966.0,
        "gini": 53.1,
    },
    {
        "name": "Benin",
        "capital": "Porto-Novo",
        "region": "Africa",
        "subregion": "Western Africa",
        "population": 10653654,
        "area": 112622.0,
        "gini": 38.6,
    },
    {
        "name": "Bermuda",
        "capital": "Hamilton",
        "region": "Americas",
        "subregion": "Northern America",
        "population": 61954,
        "area": 54.0,
    },
    {
        "name": "Bhutan",
        "capital": "Thimphu",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 775620,
        "area": 38394.0,
        "gini": 38.1,
    },
    {
        "name": "Bolivia (Plurinational State of)",
        "capital": "Sucre",
        "region": "Americas",
        "subregion": "South America",
        "population": 10985059,
        "area": 1098581.0,
        "gini": 56.3,
    },
    {
        "name": "Bonaire, Sint Eustatius and Saba",
        "capital": "Kralendijk",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 17408,
        "area": 294.0,
    },
    {
        "name": "Bosnia and Herzegovina",
        "capital": "Sarajevo",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 3531159,
        "area": 51209.0,
        "gini": 36.2,
    },
    {
        "name": "Botswana",
        "capital": "Gaborone",
        "region": "Africa",
        "subregion": "Southern Africa",
        "population": 2141206,
        "area": 582000.0,
        "gini": 61.0,
    },
    {
        "name": "Bouvet Island",
        "capital": "",
        "region": "",
        "subregion": "",
        "population": 0,
        "area": 49.0,
    },
    {
        "name": "Brazil",
        "capital": "Brasília",
        "region": "Americas",
        "subregion": "South America",
        "population": 206135893,
        "area": 8515767.0,
        "gini": 54.7,
    },
    {
        "name": "British Indian Ocean Territory",
        "capital": "Diego Garcia",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "population": 3000,
        "area": 60.0,
    },
    {
        "name": "United States Minor Outlying Islands",
        "capital": "",
        "region": "Americas",
        "subregion": "Northern America",
        "population": 300,
    },
    {
        "name": "Virgin Islands (British)",
        "capital": "Road Town",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 28514,
        "area": 151.0,
    },
    {
        "name": "Virgin Islands (U.S.)",
        "capital": "Charlotte Amalie",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 114743,
        "area": 346.36,
    },
    {
        "name": "Brunei Darussalam",
        "capital": "Bandar Seri Begawan",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "population": 411900,
        "area": 5765.0,
    },  
    {
        "name": "Montenegro",
        "capital": "Podgorica",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 621810,
        "area": 13812.0,
        "gini": 30.0,
    },
    {
        "name": "Montserrat",
        "capital": "Plymouth",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 4922,
        "area": 102.0,
    },
    {
        "name": "Morocco",
        "capital": "Rabat",
        "region": "Africa",
        "subregion": "Northern Africa",
        "population": 33337529,
        "area": 446550.0,
        "gini": 40.9,
    },
    {
        "name": "Mozambique",
        "capital": "Maputo",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "population": 26423700,
        "area": 801590.0,
        "gini": 45.7,
    },
    {
        "name": "Myanmar",
        "capital": "Naypyidaw",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "population": 51419420,
        "area": 676578.0,
    },
    {
        "name": "Namibia",
        "capital": "Windhoek",
        "region": "Africa",
        "subregion": "Southern Africa",
        "population": 2324388,
        "area": 825615.0,
        "gini": 63.9,
    },
    {
        "name": "Nauru",
        "capital": "Yaren",
        "region": "Oceania",
        "subregion": "Micronesia",
        "population": 10084,
        "area": 21.0,
    },
    {
        "name": "Nepal",
        "capital": "Kathmandu",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 28431500,
        "area": 147181.0,
        "gini": 32.8,
    },
    {
        "name": "Netherlands",
        "capital": "Amsterdam",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 17019800,
        "area": 41850.0,
        "gini": 30.9,
    },
    {
        "name": "New Caledonia",
        "capital": "Nouméa",
        "region": "Oceania",
        "subregion": "Melanesia",
        "population": 268767,
        "area": 18575.0,
    },
    {
        "name": "New Zealand",
        "capital": "Wellington",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": 4697854,
        "area": 270467.0,
        "gini": 36.2,
    },
    {
        "name": "Nicaragua",
        "capital": "Managua",
        "region": "Americas",
        "subregion": "Central America",
        "population": 6262703,
        "area": 130373.0,
        "gini": 40.5,
    },
    {
        "name": "Niger",
        "capital": "Niamey",
        "region": "Africa",
        "subregion": "Western Africa",
        "population": 20715000,
        "area": 1267000.0,
        "gini": 34.6,
    },
    {
        "name": "Nigeria",
        "capital": "Abuja",
        "region": "Africa",
        "subregion": "Western Africa",
        "population": 186988000,
        "area": 923768.0,
        "gini": 48.8,
    },
    {
        "name": "Niue",
        "capital": "Alofi",
        "region": "Oceania",
        "subregion": "Polynesia",
        "population": 1470,
        "area": 260.0,
    },
    {
        "name": "Norfolk Island",
        "capital": "Kingston",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": 2302,
        "area": 36.0,
    },
    {
        "name": "Korea (Democratic People's Republic of)",
        "capital": "Pyongyang",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "population": 25281000,
        "area": 120538.0,
    },
    {
        "name": "Northern Mariana Islands",
        "capital": "Saipan",
        "region": "Oceania",
        "subregion": "Micronesia",
        "population": 56940,
        "area": 464.0,
    },
    {
        "name": "Norway",
        "capital": "Oslo",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 5223256,
        "area": 323802.0,
        "gini": 25.8,
    },
    {
        "name": "Oman",
        "capital": "Muscat",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 4420133,
        "area": 309500.0,
    },
    {
        "name": "Pakistan",
        "capital": "Islamabad",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 194125062,
        "area": 881912.0,
        "gini": 30.0,
    },
    {
        "name": "Palau",
        "capital": "Ngerulmud",
        "region": "Oceania",
        "subregion": "Micronesia",
        "population": 17950,
        "area": 459.0,
    },
]

zadany_region = input("Zadej region:")
for stat in staty:
    if stat["region"] == zadany_region:
        print(stat["name"])


region_existuje = False
for region in staty:
   if stat["region"] == zadany_region:
        region_existuje = True

if region_existuje == False:
     print("Neznamy region")